typography_spectrum: 0.604347042972222
color:
  brandColors:
    - '#ed3237'
    - '#4b4b4d'
    - '#000000'
    - '#bf0000'
    - '#ff0000'
  brandStrength: 0.31685260217636824
  lightness: 0.9458084027282894
  saturation: 0.7060159721877426
  rhythmicContrast: 0.1645478568971157
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7867253536824137
analytics:
  google: null
  facebook: null
  twitter: null
name: The Viking Ditte
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact Form!
    url: 'https://wix.123contactform.com/form-2167846/Extra-200-Campaign'
    type: external
favicon: null
title: Ditte Westbury
description: Fighting for the right loan for you!
purpose: []
